[package]
name = "murder-client"
version = "0.1.0"
authors = ["Will Hunt <half-shot@molrams.com>"]
licence = "MIT"

[dependencies]
murder = { path = "../murder"}
rand = "0.3.15"
slog = "1.4.0"
slog-term = "1.3.4"
